/* navigator.js — cross-document topic navigator */

// ─── State ──────────────────────────────────────────────────────
let indexData       = null;
let activeTopic     = null;
let activeDocFilter = null;
let conflictOnly    = false;
let searchQuery     = '';
let activeChunkIdx  = null;

const DOC_COLORS = [
  { bg: '#E6F1FB', text: '#0C447C', dot: '#185FA5' },
  { bg: '#E1F5EE', text: '#085041', dot: '#0F6E56' },
  { bg: '#FAEEDA', text: '#633806', dot: '#854F0B' },
  { bg: '#FAECE7', text: '#712B13', dot: '#993C1D' },
  { bg: '#EEEDFE', text: '#3C3489', dot: '#534AB7' },
  { bg: '#EAF3DE', text: '#27500A', dot: '#3B6D11' },
];

const TOPIC_ICONS = {
  'Housing':         'ti-building',
  'Environment':     'ti-leaf',
  'Transport':       'ti-train',
  'Health':          'ti-heart-rate-monitor',
  'Education':       'ti-school',
  'Economy & Fiscal':'ti-chart-line',
  'Infrastructure':  'ti-hammer',
  'Social Services': 'ti-users',
  'Energy':          'ti-bolt',
  'Water':           'ti-droplet',
  'Justice & Police':'ti-shield',
};
function iconFor(topic) {
  return TOPIC_ICONS[topic] || 'ti-tag';
}

// ─── Init ────────────────────────────────────────────────────────
window.addEventListener('DOMContentLoaded', () => {
  const raw = localStorage.getItem('docnav_index');
  if (raw) {
    try { loadIndex(JSON.parse(raw)); } catch { showNoIndex(); }
  } else {
    showNoIndex();
  }
  updateIndexStatus();
});

function showNoIndex() {
  document.getElementById('noIndexState').style.display  = 'flex';
  document.getElementById('navigatorUI').style.display   = 'none';
}

function showNavigator() {
  document.getElementById('noIndexState').style.display  = 'none';
  document.getElementById('navigatorUI').style.display   = 'flex';
}

// ─── Load index ──────────────────────────────────────────────────
function loadIndex(data) {
  indexData = data;
  renderTopicList();
  renderDocFilters();
  showNavigator();
  updateIndexStatus();
}

function loadIndexFile(event) {
  const file = event.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = e => {
    try {
      const data = JSON.parse(e.target.result);
      localStorage.setItem('docnav_index', JSON.stringify(data));
      loadIndex(data);
    } catch {
      alert('Could not parse index.json — make sure it was generated by the pipeline.');
    }
  };
  reader.readAsText(file);
  event.target.value = '';
}

function updateIndexStatus() {
  const el  = document.getElementById('indexStatus2');
  if (!el) return;
  if (indexData) {
    const gen = indexData.generated
      ? new Date(indexData.generated).toLocaleDateString('en-AU', { day: 'numeric', month: 'short' })
      : '';
    el.textContent = `${indexData.chunks?.length || 0} chunks${gen ? ' · ' + gen : ''}`;
  } else {
    el.textContent = 'No index loaded';
  }
}

// ─── Topic list ──────────────────────────────────────────────────
function renderTopicList() {
  if (!indexData) return;
  const counts = {};
  indexData.chunks.forEach(c => (c.topics || []).forEach(t => {
    counts[t] = (counts[t] || 0) + 1;
  }));

  const sorted = Object.entries(counts).sort((a, b) => b[1] - a[1]);
  const el = document.getElementById('topicList');
  el.innerHTML = sorted.map(([topic, count]) => `
    <button class="topic-btn${activeTopic === topic ? ' active' : ''}"
            onclick="selectTopic('${esc(topic)}')">
      <i class="ti ${iconFor(topic)}"></i>
      ${esc(topic)}
      <span class="topic-count">${count}</span>
    </button>
  `).join('');
}

function selectTopic(topic) {
  activeTopic  = topic;
  conflictOnly = false;
  document.getElementById('clearTopicBtn').style.display = 'inline';
  renderTopicList();
  renderResults();
}

function clearTopic() {
  activeTopic  = null;
  conflictOnly = false;
  document.getElementById('clearTopicBtn').style.display = 'none';
  renderTopicList();
  renderResults();
}

// ─── Doc filters ─────────────────────────────────────────────────
function renderDocFilters() {
  if (!indexData) return;
  const docs = indexData.documents || [];
  const el   = document.getElementById('docFilterList');
  el.innerHTML = docs.map((d, i) => {
    const dc = DOC_COLORS[i % DOC_COLORS.length];
    return `
      <button class="doc-filter-btn${activeDocFilter === d.docIndex ? ' active' : ''}"
              onclick="toggleDocFilter(${d.docIndex})">
        <span class="doc-dot" style="background:${dc.dot}"></span>
        ${esc(d.name)}
      </button>
    `;
  }).join('');
}

function toggleDocFilter(docIndex) {
  activeDocFilter = (activeDocFilter === docIndex) ? null : docIndex;
  renderDocFilters();
  renderResults();
}

// ─── Search ──────────────────────────────────────────────────────
function onSearch(val) {
  searchQuery  = val.trim().toLowerCase();
  activeTopic  = null;
  conflictOnly = false;
  document.getElementById('clearTopicBtn').style.display = 'none';
  renderTopicList();
  renderResults();
}

// ─── Conflict filter ─────────────────────────────────────────────
function toggleConflictFilter() {
  conflictOnly = !conflictOnly;
  const btn = document.getElementById('conflictFilterBtn');
  btn.style.background = conflictOnly ? 'var(--red-bg)' : '';
  btn.style.color      = conflictOnly ? 'var(--red-text)' : '';
  renderResults();
}

// ─── Filter chunks ───────────────────────────────────────────────
function getFilteredChunks() {
  if (!indexData) return [];
  let chunks = indexData.chunks;

  if (activeTopic) {
    chunks = chunks.filter(c => (c.topics || []).includes(activeTopic));
  }
  if (searchQuery) {
    chunks = chunks.filter(c =>
      c.text.toLowerCase().includes(searchQuery) ||
      c.summary.toLowerCase().includes(searchQuery) ||
      (c.topics || []).some(t => t.toLowerCase().includes(searchQuery))
    );
  }
  if (activeDocFilter !== null) {
    chunks = chunks.filter(c => c.docIndex === activeDocFilter);
  }
  if (conflictOnly) {
    chunks = chunks.filter(c => c.conflict_signal);
  }
  return chunks;
}

// ─── Render results ───────────────────────────────────────────────
function renderResults() {
  const chunks = getFilteredChunks();
  const header = document.getElementById('resultsHeader');
  const title  = document.getElementById('resultsTitle');
  const sub    = document.getElementById('resultsSub');
  const list   = document.getElementById('resultsList');
  const cfBtn  = document.getElementById('conflictFilterBtn');
  const synth  = document.getElementById('synthesisBanner');

  header.style.display = 'flex';

  if (activeTopic) {
    title.textContent = activeTopic;
    const conflictCount = chunks.filter(c => c.conflict_signal).length;
    sub.textContent = `${chunks.length} passage${chunks.length !== 1 ? 's' : ''} across ${countDocs(chunks)} document${countDocs(chunks) !== 1 ? 's' : ''}${conflictCount ? ` · ${conflictCount} conflict signal${conflictCount > 1 ? 's' : ''}` : ''}`;
    cfBtn.style.display = chunks.some(c => c.conflict_signal) ? 'inline-flex' : 'none';
    renderSynthesis(chunks);
  } else if (searchQuery) {
    title.textContent = `"${searchQuery}"`;
    sub.textContent   = `${chunks.length} result${chunks.length !== 1 ? 's' : ''}`;
    cfBtn.style.display = 'none';
    synth.style.display = 'none';
  } else {
    title.textContent   = 'All passages';
    sub.textContent     = `${chunks.length} total`;
    cfBtn.style.display = 'none';
    synth.style.display = 'none';
  }

  if (!chunks.length) {
    list.innerHTML = `<div class="empty-results">
      <i class="ti ti-search-off"></i>
      <p>${activeTopic ? 'No passages match this topic and filter combination.' : 'No results found.'}</p>
    </div>`;
    return;
  }

  list.innerHTML = chunks.map((c, i) => {
    const dc = DOC_COLORS[c.docIndex % DOC_COLORS.length];
    const doc = indexData.documents?.[c.docIndex];
    return `
      <div class="result-card${c.conflict_signal ? ' has-conflict' : ''}">
        <div class="rc-header">
          <span class="doc-pill" style="background:${dc.bg};color:${dc.text};font-size:11px;padding:2px 8px;border-radius:10px;font-weight:500">
            ${esc(c.document)}
          </span>
          <span class="rc-section">${esc(sectionLabel(c))}</span>
          <span class="rc-page"><i class="ti ti-file-text" style="font-size:11px"></i> p.${c.pages.start}${c.pages.start !== c.pages.end ? '–' + c.pages.end : ''}</span>
        </div>
        <div class="rc-body"><p>${esc(c.summary)}</p></div>
        <div class="rc-footer">
          ${(c.topics || []).map(t => `<span class="rc-tag">${esc(t)}</span>`).join('')}
          ${(c.figures || []).map(f => `<span class="rc-tag" style="background:var(--amber-bg);color:var(--amber-text);border-color:transparent">${esc(f)}</span>`).join('')}
          ${c.conflict_signal ? `<span class="rc-conflict-badge"><i class="ti ti-alert-triangle" style="font-size:10px"></i> review</span>` : ''}
          <button class="rc-source-btn" onclick="openSource(${i}, ${JSON.stringify(chunks).length > 0 ? 'chunks' : '[]'})">
            <i class="ti ti-eye" style="font-size:11px"></i> Source
          </button>
        </div>
      </div>
    `;
  }).join('');

  // Store current chunks on window for source lookup
  window._currentChunks = chunks;
}

function countDocs(chunks) {
  return new Set(chunks.map(c => c.docIndex)).size;
}

function sectionLabel(chunk) {
  // Use first 60 chars of text as a pseudo-section label if no heading info
  return chunk.text.slice(0, 60).replace(/\n/g, ' ').trim() + '…';
}

// ─── Synthesis banner ────────────────────────────────────────────
function renderSynthesis(chunks) {
  const synth = document.getElementById('synthesisBanner');
  const text  = document.getElementById('synthesisText');

  if (!chunks.length) { synth.style.display = 'none'; return; }

  const docNames    = [...new Set(chunks.map(c => c.document))];
  const allFigures  = [...new Set(chunks.flatMap(c => c.figures || []))].slice(0, 4);
  const conflicts   = chunks.filter(c => c.conflict_signal).length;

  let summary = `Found in <strong>${docNames.length} document${docNames.length > 1 ? 's' : ''}</strong>: ${docNames.map(d => `<em>${esc(d)}</em>`).join(', ')}.`;
  if (allFigures.length) summary += ` Key figures: ${allFigures.map(f => `<strong>${esc(f)}</strong>`).join(', ')}.`;
  if (conflicts)         summary += ` <span style="color:var(--red-text)">⚠ ${conflicts} passage${conflicts > 1 ? 's' : ''} flagged for review.</span>`;

  text.innerHTML      = summary;
  synth.style.display = 'flex';
}

function askClaude() {
  const chunks = window._currentChunks || [];
  const topic  = activeTopic || searchQuery || 'this topic';
  const docList = [...new Set(chunks.map(c => c.document))].join(', ');
  // Opens Claude.ai with a prompt — adjust if you want to call the API directly
  const prompt = encodeURIComponent(
    `I have these passages about "${topic}" from the following documents: ${docList}.\n\n` +
    chunks.slice(0, 5).map(c => `[${c.document} p.${c.pages.start}]: ${c.summary}`).join('\n') +
    `\n\nCan you synthesise these, identify key themes, flag any contradictions, and summarise the overall picture?`
  );
  window.open(`https://claude.ai/new?q=${prompt}`, '_blank');
}

// ─── Source panel ────────────────────────────────────────────────
function openSource(idx) {
  const chunks = window._currentChunks || [];
  const c = chunks[idx];
  if (!c) return;
  activeChunkIdx = idx;

  const dc  = DOC_COLORS[c.docIndex % DOC_COLORS.length];
  const panel = document.getElementById('sourcePanel');
  const body  = document.getElementById('sourcePanelBody');

  document.getElementById('sourcePanelTitle').textContent = `${c.document} · p.${c.pages.start}`;

  body.innerHTML = `
    <div class="source-doc-label">${esc(c.document)}</div>
    <div class="source-excerpt">${esc(c.text)}</div>
    <div class="source-meta">
      <span>Pages ${c.pages.start}–${c.pages.end}</span>
    </div>
    <hr class="source-divider" />
    <div class="source-doc-label">Topics</div>
    <div style="display:flex;gap:5px;flex-wrap:wrap;margin-bottom:12px">
      ${(c.topics || []).map(t => `<span class="rc-tag">${esc(t)}</span>`).join('')}
    </div>
    ${(c.figures || []).length ? `
      <div class="source-doc-label">Key figures</div>
      <div style="display:flex;gap:5px;flex-wrap:wrap;margin-bottom:12px">
        ${c.figures.map(f => `<span class="rc-tag" style="background:var(--amber-bg);color:var(--amber-text);border-color:transparent">${esc(f)}</span>`).join('')}
      </div>
    ` : ''}
    ${(c.dates || []).length ? `
      <div class="source-doc-label">Dates mentioned</div>
      <div style="display:flex;gap:5px;flex-wrap:wrap;margin-bottom:12px">
        ${c.dates.map(d => `<span class="rc-tag">${esc(d)}</span>`).join('')}
      </div>
    ` : ''}
    ${c.conflict_signal ? `
      <hr class="source-divider" />
      <div class="source-conflict-box">
        <strong><i class="ti ti-alert-triangle"></i> Review flagged</strong><br>
        Claude detected that this passage may contain a figure or date that conflicts with another value in the same document or related documents. Cross-check manually.
      </div>
    ` : ''}
  `;

  panel.style.display = 'flex';
}

function closeSource() {
  document.getElementById('sourcePanel').style.display = 'none';
  activeChunkIdx = null;
}

// ─── Export briefing ─────────────────────────────────────────────
function exportBriefing() {
  const chunks = window._currentChunks || indexData?.chunks || [];
  const topic  = activeTopic || 'All topics';
  const lines  = [
    `# Document briefing: ${topic}`,
    `Generated: ${new Date().toLocaleString('en-AU')}`,
    '',
    `## Summary`,
    `${chunks.length} passages across ${countDocs(chunks)} document(s).`,
    '',
  ];
  const byDoc = {};
  chunks.forEach(c => {
    if (!byDoc[c.document]) byDoc[c.document] = [];
    byDoc[c.document].push(c);
  });
  for (const [doc, cs] of Object.entries(byDoc)) {
    lines.push(`## ${doc}`);
    cs.forEach(c => {
      lines.push(`\n### p.${c.pages.start}–${c.pages.end}`);
      lines.push(c.summary);
      if (c.figures?.length) lines.push(`**Figures:** ${c.figures.join(', ')}`);
      if (c.conflict_signal)  lines.push(`> ⚠ Conflict review flagged`);
    });
    lines.push('');
  }

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  const a    = document.createElement('a');
  a.href     = URL.createObjectURL(blob);
  a.download = `briefing_${topic.replace(/\W+/g,'_')}.md`;
  a.click();
  URL.revokeObjectURL(a.href);
}

// ─── Utils ───────────────────────────────────────────────────────
function esc(s) {
  return String(s ?? '')
    .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    .replace(/"/g,'&quot;');
}